---
# Playbook to pull native data from IOSXE devices

- name: "Play 1: RESTCONF Playbook"
  hosts: cisco_iosxe
  connection: local
  tasks:
    - name: "Task 1 - pull information from hosts"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: result
   
    - name: "Print Result"
      debug:
        msg: "{{ result.json }}"
  